apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app.kubernetes.io/part-of: application-1
    app.kubernetes.io/name: analytics
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: user-analytics
    app.kubernetes.io/version: "1.0"
  annotations:
    app.openshift.io/vcs-uri: "https://github.com/redhat-developer/topology-example"
    app.openshift.io/vcs-ref: "v1.0.0"
spec:
  ports:
    - port: 80
