apiVersion: v1
kind: Service
metadata:
  name: wit-service
  labels:
    app.kubernetes.io/part-of: application-1
    app.kubernetes.io/name: wit
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: wit-1
    app.kubernetes.io/version: "1.0"
  annotations:
    app.openshift.io/vcs-uri: "git@github.com:redhat-developer/topology-example.git"
    app.openshift.io/vcs-ref: "v1.0.0"
spec:
  ports:
    - port: 80


